/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebookproject;

/**
 *
 * @author Samyan
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXMonthView1 = new org.jdesktop.swingx.JXMonthView();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();

        jXLabel1.setText("jXLabel1");

        setLayout(new java.awt.BorderLayout());

        jXMonthView1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jXMonthView1, java.awt.BorderLayout.WEST);

        jXHeader1.setDescriptionFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXHeader1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jXHeader1.setTitle("Dashboard -- Phone Book Manaement System");
        add(jXHeader1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This is the a demo for Phonebook app. Dashboard can be customized according to needs. This demo contains the following features.\n1. CRUD operations\n2. File Handling \n3. Responsive Layout\n\nThis dashboard is just a UI and does not contain any functionality.\nData addtion/updation does not contain any validation currently. You can add on your own.");
        jPanel1.add(jTextArea1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jXTaskPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXTaskPane1.setSpecial(true);
        jXTaskPane1.setTitle("Contacts - Upcoming Birthdays ");
        add(jXTaskPane1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXMonthView jXMonthView1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    // End of variables declaration//GEN-END:variables
}
